### ISSUE TITLE
Where to find yalla command line guide?

### ISSUE THREAD

**Issue by Velliz** [yallajs/yalla#1]
When trying running trough node server.
I realize that template need to re-compile every time i made change.

Would be nice if yalla command line have something like:
```
yalla -h
yalla -help
yalla help
```

To provide clear step how far we can do with the yalla framework.
Thanks :D

**Comment by yallajs** [comment]
Hi Velliz,

Thank you for your feed back  👍. Will introduce the help in CLI very soon.

Thank you so much,

**Comment by Velliz** [comment]
Thanks for response.
I will wait for that 👍

**Comment by yallajs** [comment]
Yalla command line no longer required in 2.0, please comeback at 20 october 2017 :)
